spring:
  application:
    name: Java-Spring-Lessons
  datasource:
    url: jdbc:postgresql://localhost:5432/studyDb
    username: postgres
    password: 9476
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    properties.hibernate:
      show-sql: true
      format_sql: true
      hbm2ddl:
        auto: validate