spring:
  application.name: Java-Spring-Lessons

server:
  port: 8282

app:
  env-value: ${APP_ENV:default}
  name: "Java-Spring-Lessons-Prod"
  values:
    - 1
    - -1
  db:
    url: "jdbc:someSql://devPath/devDb"